import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import AlertWrapper from "./components/Alert/AlertWrapper";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GamePage",
  description: "Generated by create next app",
  icons: {
    icon: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><polygon points='50,15 61,45 95,45 67,65 78,95 50,75 22,95 33,65 5,45 39,45' fill='%23ffd700'/></svg>",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased`}>
        <div id="modal-root"></div>
        <Providers>
          <>
            <Header />
            {children}
            <Footer />
            <AlertWrapper />
          </>
        </Providers>
      </body>
    </html>
  );
}
