import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "./components/ReduxProvider/ReduxProvider";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Game_Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`} ${inter.variable} antialiased`}>
        <ReduxProvider>
          <>
            <Header />
            {children}
            <Footer />
          </>
        </ReduxProvider>
      </body>
    </html>
  );
}
