import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import AlertWrapper from "./components/Alert/AlertWrapper";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Game_Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} antialiased`}>
        <div id="modal-root"></div>
        <Providers>
          <>
            <Header />
            {children}
            <Footer />
            <AlertWrapper />
          </>
        </Providers>
      </body>
    </html>
  );
}
